title: Digital Toolkit Test
description: It's our first try to set up a curated collection of new and
existing digital self-learning materials to make learning comftable. 
remote_theme: pmarsceill/just-the-docs

url: https://datatrainubra.github.io/DigitalToolkitTest/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
