title: Just the Docs Template
description: A starter template for a Jekyll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs

url: https://datatrainubra.github.io/DigitalToolkitTest/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
